name = "reminder-bot"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
BOT_TOKEN = ""
BOT_USERNAME = ""
PROJECT_TITLE = ""
START_DATE = ""
END_DATE = ""

[[kv_namespaces]]
binding = "ACTIVE_CHATS"
id = ""
preview_id = ""

[triggers]
crons = ["0 0 * * *"]  # Run at midnight every day