name = "reminder-bot"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
BOT_TOKEN = ""
BOT_USERNAME = ""
PROJECT_TITLE = ""
START_DATE = ""
END_DATE = ""

[[kv_namespaces]]
binding = "ACTIVE_CHATS"
id = "e0163c6cd91a47d9bfc992736a119b6a"
preview_id = "e0163c6cd91a47d9bfc992736a119b6a"

[triggers]
crons = ["0 0 * * *"]  # Run at midnight every day